# Generated by Django 4.2 on 2023-04-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postsmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
